IMAGE_NAME = "centos/7"

# MASTER vm's
M=1

Vagrant.configure('2') do |configmaster|
  configmaster.vm.synced_folder '.', '/vagrant', disabled: true
  
  (1..M).each do |i|
        configmaster.vm.define "master-#{i}" do |master|
            master.vm.box = IMAGE_NAME
            master.vm.network "private_network", ip: "192.168.56.#{i + 120}"
            master.vm.hostname = "master#{i}.mykubecluster.com"
            master.vm.provider "virtualbox" do |v|
                v.memory = "2048"
                v.cpus = "2"
            end
            master.vm.provision "shell", path: "scripts/kube-pre-req.sh"
            master.vm.provision "shell", path: "scripts/bootstrap-master.sh"
   end

end 

end


# NODE vm's
N=2

Vagrant.configure('2') do |config1|
  config1.vm.synced_folder '.', '/vagrant', disabled: true

  (1..N).each do |i|
        config1.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.56.#{i + 120 + M}"
            #node.vm.network "public_network", ip: "10.0.0.234"
            node.vm.hostname = "node#{i}.mykubecluster.com"
            node.vm.provider "virtualbox" do |v|
                v.memory = "2048"
                v.cpus = "1"
            end
            node.vm.provision "shell", path: "scripts/kube-pre-req.sh"
            node.vm.provision "shell", path: "scripts/bootstrap-node.sh"
   end

end 

end




